# Generated by Django 3.1.5 on 2021-07-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sipariş_detay', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'sipariş',
                'verbose_name_plural': 'siparişler',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'iletişim', 'verbose_name_plural': 'iletişim'},
        ),
    ]
